pegasus/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Redis;

Route::get('sockets', function () {
    $m = new \App\Models\Messaging\Message;
    $m->user_id = 1;
    event(new \App\Events\Messaging\NewMessage($m));
    return 'Event sent';
})->name('test');

Route::get('sockets-test', function () {
    return view('sockets');
})->name('test');

// Social OAuth routes
Route::get('auth/{provider}', 'Auth\OAuthController@redirectToProvider')
    ->name('oauth')
    ->where(['provider' => '(github|google|bitbucket)']);

Route::get('auth/{provider}/callback', 'Auth\OAuthController@handleProviderCallback')
    ->where(['provider' => '(github|google|bitbucket)']);

// Api routes
Route::group(['as' => 'api.', 'prefix' => 'api'], function () {

    Route::resource('users', 'UserController');

    Route::group(['as' => 'users.websites', 'prefix' => 'users/websites'], function () {
        Route::post('/', 'UserWebsiteController@create');
        Route::get('/{userId}/{websiteId}', 'UserWebsiteController@show');
        Route::put('/{userId}/{websiteId}', 'UserWebsiteController@update');
        Route::patch('/{userId}/{websiteId}', 'UserWebsiteController@update');
        Route::delete('/{userId}/{websiteId}', 'UserWebsiteController@destroy');
    });
    // Users
    Route::group(['as' => 'users.', 'prefix' => 'users'], function () {

        // Authentication routes
        Route::group(['as' => 'auth.', 'prefix' => 'current'], function () {

            Route::get('current', 'Auth\UserController@getCurrent')
                ->middleware(['auth'])
                ->name('current');

            // Authentication Routes...
            Route::get('login', 'Auth\LoginController@showLoginForm')
                ->name('getLogin');
            Route::post('login', 'Auth\LoginController@login')
                ->name('postLogin');
            Route::post('auth/login', 'Auth\LoginController@login')
                ->name('authpostLogin');

            // Registration Routes...
            Route::get('register', 'Auth\RegisterController@showRegistrationForm')
                ->name('getRegister');
            Route::post('register', 'Auth\RegisterController@register')
                ->name('postRegister');

            // Password Reset Routes...
            Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')
                ->name("getPasswordReset");
            Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')
                ->name("postPasswordResetEmail");
        });
    });

    // Threads
    Route::group(['as' => 'threads.', 'prefix' => 'threads'], function () {
        Route::post('/', 'ThreadController@store');
        Route::get('/', 'ThreadController@index');
        Route::post('{threadId}/message', 'MessageController@create');
    });

    // Messages
    Route::group(['as' => 'messages.', 'prefix' => 'messages'], function () {
        Route::post('/new', 'MessageController@new');
        Route::get('/', 'MessageController@index');
        Route::post('{threadId}/message', 'MessageController@create');
    });

    // Projects
    Route::group(['as' => 'projects.', 'prefix' => 'projects'], function () {
        Route::post('/', 'ProjectController@create')->name('create');
        Route::get('/', 'ProjectController@index')->name('index');
        Route::get('{id}', 'ProjectController@show')->name('show');
        Route::put('{id}', 'ProjectController@update')->name('update');
        Route::patch('{id}', 'ProjectController@update')->name('update');
    });
});

Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')
    ->name("auth.getPasswordResetForm");
Route::post('password/reset', 'Auth\ResetPasswordController@reset')
    ->name("auth.postPasswordReset");

Route::get('logout', 'Auth\LoginController@logout')
    ->name('logout');

Route::get('/', function () {
    return view('layouts.spalayout');
})->name('home');

Route::get('{any}', function () {
    return view('layouts.spalayout');
})
->where('any', '(.*)')
->name('spa');

pegasus/resources/views/partials/master/errors.blade.php
@if($errors->count() > 0)
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-danger">
        	<ul>
        		@foreach($errors->all() as $error)
        		<li>{{ $error }}</li>
        		@endforeach
        	</ul>
    	</div>
    </div>
</div>
@endif

pegasus/resources/views/partials/master/header.blade.php
<header id="header" class="@if(Route::current()->getName() == 'home') alt @endif skel-layers-fixed">
    <h1><a href="{{ route('home') }}">Pegasus <span>collaboration platform</span></a></h1>
    <nav id="nav">
        <ul>
            <li><a href="{{ route('home') }}">Home</a></li>
            <li>
                <a href="" class="icon fa-angle-down">HTML Template</a>
                <ul>
                    <li><a href="{{ route('elements.showcase') }}">Showcase</a></li>
                    <li><a href="{{ route('elements.left_sidebar') }}">Left sidebar</a></li>
                    <li><a href="{{ route('elements.right_sidebar') }}">Right sidebar</a></li>
                    <li><a href="{{ route('elements.no_sidebar') }}">No sidebar</a></li>
                </ul>
            </li>
            <li>
                @if(Auth::check())
                    <a href="" class="icon fa-angle-down">{{ Auth::user()->email}}</a>
                    <ul>
                        <li><a href="{{ route('auth.logout') }}">Log out</a></li>
                        @can('users.index')
                            <li><a href="{{ route('users.index') }}">All users</a></li>
                        @endcan
                    </ul>
                @else
                    <a href="" class="icon fa-angle-down">User</a>
                    <ul>
                        <li><a href="{{ route('auth.getRegister') }}">Register</a></li>
                        <li><a href="{{ route('auth.getLogin') }}">Log in</a></li>
                        <li><a href="{{ route('auth.getPasswordReset') }}">Forgot password</a></li>
                        <li>
                            <a href="">Submenu</a>
                            <ul>
                                <li><a href="#">Option 1</a></li>
                                <li><a href="#">Option 2</a></li>
                                <li><a href="#">Option 3</a></li>
                                <li><a href="#">Option 4</a></li>
                            </ul>
                        </li>
                    </ul>
                @endif
            </li>
        </ul>
    </nav>
</header>

pegasus/resources/views/partials/master/status.blade.php
@if((!isset($hide_status_modal) || !$hide_status_modal) && ($errors->count() > 0 || request()->session()->has('success')))
<div class="modal fade in" data-show="true" id="statusModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Status</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        @include('partials.master.errors')
        @include('partials.master.success')
      </div>
      <div class="modal-footer">
        <button type="button" class="button" data-dismiss="modal">Close</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">$("#statusModal").modal("show");</script>
@endif

pegasus/resources/views/partials/master/success.blade.php
@if(request()->session()->has('success'))
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-success">
            <ul>
                @foreach(request()->session()->get('success')->all() as $success)
                <li>{{ $success }}</li>
                @endforeach
            </ul>
    	</div>
    </div>
</div>
@endif