pegasus/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Redis;

Route::get('sockets', function () {
    $m = new \App\Models\Messaging\Message;
    $m->user_id = 1;
    event(new \App\Events\Messaging\NewMessage($m));
    return 'Event sent';
})->name('test');

Route::get('sockets-test', function () {
    return view('sockets');
})->name('test');

// Social OAuth routes
Route::get('auth/{provider}', 'Auth\OAuthController@redirectToProvider')
    ->name('oauth')
    ->where(['provider' => '(github|google|bitbucket)']);

Route::get('auth/{provider}/callback', 'Auth\OAuthController@handleProviderCallback')
    ->where(['provider' => '(github|google|bitbucket)']);

// Api routes
Route::group(['as' => 'api.', 'prefix' => 'api'], function () {

    Route::resource('users', 'UserController');

    Route::group(['as' => 'users.websites', 'prefix' => 'users/websites'], function () {
        Route::post('/', 'UserWebsiteController@create');
        Route::get('/{userId}/{websiteId}', 'UserWebsiteController@show');
        Route::put('/{userId}/{websiteId}', 'UserWebsiteController@update');
        Route::patch('/{userId}/{websiteId}', 'UserWebsiteController@update');
        Route::delete('/{userId}/{websiteId}', 'UserWebsiteController@destroy');
    });
    // Users
    Route::group(['as' => 'users.', 'prefix' => 'users'], function () {

        // Authentication routes
        Route::group(['as' => 'auth.', 'prefix' => 'current'], function () {

            Route::get('current', 'Auth\UserController@getCurrent')
                ->middleware(['auth'])
                ->name('current');

            // Authentication Routes...
            Route::get('login', 'Auth\LoginController@showLoginForm')
                ->name('getLogin');
            Route::post('login', 'Auth\LoginController@login')
                ->name('postLogin');
            Route::post('auth/login', 'Auth\LoginController@login')
                ->name('authpostLogin');

            // Registration Routes...
            Route::get('register', 'Auth\RegisterController@showRegistrationForm')
                ->name('getRegister');
            Route::post('register', 'Auth\RegisterController@register')
                ->name('postRegister');

            // Password Reset Routes...
            Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')
                ->name("getPasswordReset");
            Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')
                ->name("postPasswordResetEmail");
        });
    });

    // Threads
    Route::group(['as' => 'threads.', 'prefix' => 'threads'], function () {
        Route::post('/', 'ThreadController@store');
        Route::get('/', 'ThreadController@index');
        Route::post('{threadId}/message', 'MessageController@create');
    });

    // Messages
    Route::group(['as' => 'messages.', 'prefix' => 'messages'], function () {
        Route::post('/new', 'MessageController@new');
        Route::get('/', 'MessageController@index');
        Route::post('{threadId}/message', 'MessageController@create');
    });

    // Projects
    Route::group(['as' => 'projects.', 'prefix' => 'projects'], function () {
        Route::post('/', 'ProjectController@create')->name('create');
        Route::get('/', 'ProjectController@index')->name('index');
        Route::get('{id}', 'ProjectController@show')->name('show');
        Route::put('{id}', 'ProjectController@update')->name('update');
        Route::patch('{id}', 'ProjectController@update')->name('update');
    });
});

Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')
    ->name("auth.getPasswordResetForm");
Route::post('password/reset', 'Auth\ResetPasswordController@reset')
    ->name("auth.postPasswordReset");

Route::get('logout', 'Auth\LoginController@logout')
    ->name('logout');

Route::get('/', function () {
    return view('layouts.spalayout');
})->name('home');

Route::get('{any}', function () {
    return view('layouts.spalayout');
})
->where('any', '(.*)')
->name('spa');

pegasus/app/Models/Users/User.php
<?php

namespace App\Models\Users;

use Carbon\Carbon;
use App\Models\Roles\UserRole;
use App\Models\Messaging\Thread;
use App\Models\Users\UserWebsite;
use App\Lib\Traits\Model\Languagable;
use App\Notifications\PasswordResetNotification;
use Illuminate\Support\Facades\Config;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, Languagable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'email', 'password',
        'github_id', 'google_id', 'facebook_id',
        'twitter_id', 'bitbucket_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'id' => 'integer',
    ];

    // Relationships
    // Roles
    public function roles()
    {
        return $this->hasMany(UserRole::class);
    }

    // Messaging threads (also private messages)
    public function threads()
    {
        return $this->belongsToMany(Thread::class)
            ->withPivot(['joined', 'left'])
            ->whereNull('thread_user.left')
            ->order();
    }

    // Website links (for github and stuff)
    public function websiteLinks()
    {
        return $this->hasMany(UserWebsite::class)
            ->aUserCanHave()
            ->with('website');
    }

    // Scopes
    public function scopeByEmail($q, $email)
    {
        return $q->where('email', $email);
    }

    public function scopeByUsername($q, $username)
    {
        return $q->where('username', $username);
    }

    public function scopeBySocialId($q, $provider, $id)
    {
        return $q->where($provider . "_id", $id);
    }

    /**
     * Sets provider ID from OAuth
     * @param string $provider github|google|bitbucket
     * @param string $id       ID returned by the provider OAuth
     */
    public function setProviderId($provider, $id)
    {
        $this->{$provider . "_id"} = $id;
    }

    /**
     * Send the password reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new PasswordResetNotification($token));
    }

    /**
     * Check if the user has any of the given roles
     *
     * @param  array of strings  $roles
     * @return bool
     */
    public function hasRoles($roles)
    {
        return !!$this->roles->whereIn('role', $roles)->count();
    }

    /**
     * Check if the user has specific permission
     *
     * @param  string  $permission
     * @return bool
     */
    public function hasPermission($permission)
    {
        $configRoles = config('roles');
        foreach ($this->roles as $role) {
            if (in_array($permission, $configRoles[$role->role])) {
                return true;
            }
            return false; // wtf?
        }
    }

    // Casts created_at to unix timestamp
    public function getCreatedAtAttribute($timestamp)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $timestamp)->timestamp;
    }

    // Casts updated_at to unix timestamp
    public function getUpdatedAtAttribute($timestamp)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $timestamp)->timestamp;
    }

    // Casts updated_at to unix timestamp
    public function getDeletedAtAttribute($timestamp)
    {
        if ($timestamp === null) {
            return $timestamp;
        }
        return Carbon::createFromFormat('Y-m-d H:i:s', $timestamp)->timestamp;
    }
}

pegasus/app/Models/Users/UserWebsite.php
<?php

namespace App\Models\Users;

use Carbon\Carbon;
use App\Models\Users\User;
use App\Models\Websites\Website;
use App\Lib\Validators\UserWebsiteValidator;
use App\Models\CustomModel as Model;

class UserWebsite extends Model
{

    protected $fillable = ['url'];

    protected $casts = [
        'id' => 'integer',
        'user_id' => 'integer',
        'website_id' => 'integer',
    ];

    // Relationships
    public function website()
    {
        return $this->belongsTo(Website::class)
            ->aUserCanHave();
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    // Scopes
    public function scopeAUserCanHave($q)
    {
        return $q->whereHas('website', function ($q) {
            $q->aUserCanHave();
        });
    }

    public function scopeByIds($q, $userId, $websiteId)
    {
        return $q->where('user_id', $userId)
            ->where('website_id', $websiteId);
    }
}

pegasus/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Gate;
use App\User;
use App\UserRole;
use Illuminate\Http\Request;
use App\Repos\Contracts\UserRepositoryInterface;
use App\Updaters\Contracts\UserUpdaterInterface;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;

class UserController extends Controller
{

    // User repository
    protected $user;
    // Updates/creates users in db
    protected $updater;

    public function __construct(UserRepositoryInterface $user, UserUpdaterInterface $updater)
    {
        $this->user = $user;
        $this->updater = $updater;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        Gate::authorize('users.index', auth()->user());
        return response()->json($this->user->getPaginated(10, $request->input('page', null)));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Gate::authorize('users.create');
        return response()->json($this->updater->create($request->input()));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show($userId)
    {
        $user = $this->user->findById($userId);
        if ($user === null) {
            abort(404);
        }
        return response()->json($user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = $this->user->findById($id);
        if ($user === null) {
            abort(404);
        }
        Gate::authorize('users.update', auth()->user(), $user);
        return response()->json($this->updater->update($id, $request->input()));
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

pegasus/resources/views/users/edit.blade.php
@extends('layout.master')
@php($hide_status_modal=true)

@section('content')
<!-- Main -->
<section id="main" class="wrapper style1">
    <header class="major">
        {{-- <p>{{$roles}}</p> --}}
    </header>
    <div class="container">
        <!-- Content -->
        <section id="content">
            <h2>Edit {{$user->username}}</h2>

            @include('partials.master.errors')
            @include('partials.master.success')
            {{-- {{$errors->count()}} --}}
            <br/>
            {!! Form::model($user, ['method' => 'PUT', 'route' => ['users.update', $user]]) !!}
                <fieldset>
                    <div class="form-group">
                        {!! Form::text('username', old('username'), [
                            'placeholder'   => 'Username',
                            'class'         => 'form-control 9u 12u(3)',
                            'autofocus'     => ''
                        ]) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::text('email', old('email'), [
                            'placeholder'   => 'Email',
                            'class'         => 'form-control 9u 12u(3)',
                            'autofocus'     => ''
                        ]) !!}
                    </div>
                    <div class="form-group row">
                        @foreach($roles as $role)
                            <div class="2u 12u(3)">
                                {!! Form::checkbox('roles[]', $role, $user->hasRoles([$role]), ['id'=>'role-'.$role]) !!}
                                <label for="role-{{$role}}">
                                    {{$role}}
                                </label>
                            </div>
                        @endforeach
                    </div>


                    <!-- Change this to a button or input when using this as a form -->
                    {{-- <input type="submit" class="btn btn-lg" value="Register"/> --}}
                    {!! Form::submit('Save', ['class' => 'button']) !!}

                </fieldset>
            {!! Form::close() !!}
        </section>
    </div>
</section>
@stop

pegasus/resources/views/users/index.blade.php
@extends('layout.master')

@section('content')
<!-- Main -->
<section id="main" class="wrapper style1">
    <header class="major">
        {{-- <p>{{$roles}}</p> --}}
    </header>
    <div class="container">
        <!-- Content -->
        <section id="content">
            <a class="button pull-right" href="{{route('users.create')}}">New</a>
            <h2>Users</h2>
            <br/>
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Roles</th>
                        <th>Updated</th>
                        <th>Created</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($users as $user)
                    <tr>
                        <td>{{$user->id}}</td>
                        <td>{{$user->username}}</td>
                        <td>{{$user->email}}</td>
                        <td>
                            @foreach($user->roles as $role)
                                <span class="label label-default">{{$role->role}}</span>
                            @endforeach
                        </td>
                        <td>{{$user->updated_at}}</td>
                        <td>{{$user->created_at}}</td>
                        <td>
                            @can('view', $user)
                                <a href="{{route('users.show', $user->id)}}"><i class="fa fa-eye"></i></a>
                            @endcan
                            @can('update', $user)
                                <a href="{{route('users.edit', $user->id)}}"><i class="fa fa-pencil"></i></a>
                            @endcan
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </section>
    </div>
</section>
@stop